pub const POPULAR_CATEGORIES: &[(&str, &str, &[&str])] = &[
    (
        "culture and the arts",
        "Culture and the arts",
        &[
            "Culture",
            "The arts",
            "Humanities",
            "Classics",
            "Critical theory",
            "Cultural anthropology",
            "Clothing",
            "Folklore",
            "Food and drink",
            "Language",
            "Literature",
            "Museology",
            "Mythology",
            "Philosophy",
            "Popular culture",
            "Performing arts",
            "Dance",
            "Film",
            "Music",
            "Opera",
            "Theatre",
            "Visual arts",
            "Architecture",
            "Comics",
            "Design",
            "Drawing",
            "Animation",
            "Painting",
            "Photography",
            "Sculpture",
            "Games",
            "Toys",
            "Sports",
        ],
    ),
    (
        "geography and places",
        "Geography and places",
        &[
            "Geography",
            "Places",
            "Cartography",
            "Cities",
            "Continents",
            "Countries",
            "Deserts",
            "Environment",
            "Landforms",
            "Maps",
            "Mountains",
            "Oceans",
            "Parks",
            "Populated places",
            "Regions",
            "Rivers",
            "Subdivisions",
            "Towns",
            "Villages",
            "Water",
        ],
    ),
    (
        "health and fitness",
        "Health and fitness",
        &[
            "Health",
            "Health sciences",
            "Self-care",
            "Medicine",
            "Nursing",
            "Pharmacy",
            "Public health",
            "Dentistry",
            "Healthcare",
            "Nutrition",
            "Exercise",
            "Fitness",
            "Mental health",
            "Hygiene",
            "Disabilities",
            "Safety",
        ],
    ),
    (
        "history and events",
        "History and events",
        &[
            "History",
            "Events",
            "Ancient history",
            "Archaeology",
            "Chronology",
            "Historiography",
            "Military history",
            "Modern history",
            "World War II",
            "Ancient Rome",
            "Ancient Greece",
            "Middle Ages",
            "Cold War",
            "Historical eras",
            "Historical events",
            "Centuries",
            "Decades",
        ],
    ),
    (
        "human activities",
        "Human activities",
        &[
            "Human activities",
            "Lifestyles",
            "Agriculture",
            "Business",
            "Communication",
            "Education",
            "Entertainment",
            "Industry",
            "Leisure",
            "Mass media",
            "Military",
            "Politics",
            "Recreation",
            "Religion",
            "Science",
            "Spaceflight",
            "Sports",
            "Tourism",
            "Transport",
            "Work",
        ],
    ),
    (
        "mathematics and logic",
        "Mathematics and logic",
        &[
            "Mathematics",
            "Logic",
            "Algebra",
            "Analysis",
            "Arithmetic",
            "Calculus",
            "Combinatorics",
            "Geometry",
            "Mathematical logic",
            "Number theory",
            "Numeral systems",
            "Probability",
            "Statistics",
            "Trigonometry",
        ],
    ),
    (
        "natural and physical sciences",
        "Natural and physical sciences",
        &[
            "Natural sciences",
            "Physical sciences",
            "Astronomy",
            "Biology",
            "Chemistry",
            "Earth sciences",
            "Ecology",
            "Geology",
            "Materials science",
            "Meteorology",
            "Neuroscience",
            "Oceanography",
            "Physics",
            "Spaceflight",
            "Zoology",
        ],
    ),
    (
        "people and self",
        "People and self",
        &[
            "People",
            "Self",
            "Personal life",
            "Biographies",
            "Belief",
            "Body",
            "Character",
            "Deceased people",
            "Family",
            "Gender",
            "Humans",
            "Individual",
            "Names",
            "Personality",
            "Position",
            "Social status",
            "Subcultures",
        ],
    ),
    (
        "philosophy and thinking",
        "Philosophy and thinking",
        &[
            "Philosophy",
            "Thinking",
            "Critical thinking",
            "Decision making",
            "Ethics",
            "Epistemology",
            "Logic",
            "Mind",
            "Metaphysics",
            "Philosophers",
            "Philosophical theories",
            "Reasoning",
            "Values",
        ],
    ),
    (
        "religion and belief systems",
        "Religion and belief systems",
        &[
            "Religion",
            "Belief systems",
            "Buddhism",
            "Christianity",
            "Deities",
            "Esotericism",
            "God",
            "Hinduism",
            "Islam",
            "Judaism",
            "Mythology",
            "Religious texts",
            "Spirituality",
            "Theology",
            "Atheism",
            "Agnosticism",
        ],
    ),
    (
        "society and social sciences",
        "Society and social sciences",
        &[
            "Society",
            "Social sciences",
            "Anthropology",
            "Economics",
            "Education",
            "Ethnic groups",
            "Government",
            "International relations",
            "Law",
            "Linguistics",
            "Media",
            "Organizations",
            "Political science",
            "Psychology",
            "Sociology",
        ],
    ),
    (
        "technology and applied sciences",
        "Technology and applied sciences",
        &[
            "Technology",
            "Applied sciences",
            "Agriculture",
            "Architecture",
            "Artificial intelligence",
            "Automation",
            "Biotechnology",
            "Computer science",
            "Cybersecurity",
            "Electronics",
            "Engineering",
            "Information technology",
            "Internet",
            "Manufacturing",
            "Medicine",
            "Nanotechnology",
            "Nuclear technology",
            "Programming languages",
            "Robotics",
            "Software",
            "Telecommunications",
            "Transport",
        ],
    ),
];
